"""initial schema

Revision ID: 11c0ab19dc92
Revises: 
Create Date: 2026-07-13 20:29:08.636103

完整初始迁移：涵盖全部 22 张表，替代 main.py 中的 Base.metadata.create_all()。

对已有数据库（通过 create_all 创建）的安全策略：
  - 检测核心表是否存在，若已存在则跳过创建（幂等），仅记录日志。
  - 新数据库正常执行全部 create_table。
  - main.py 在启动时会对已有数据库执行 alembic stamp head 标记。

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.database import GUID


# revision identifiers, used by Alembic.
revision: str = '11c0ab19dc92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(bind, table_name: str) -> bool:
    """检查表是否已存在（兼容 SQLite 和 PostgreSQL）。"""
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    bind = op.get_bind()

    # ── 检测已有数据库：如果核心表已存在，说明是通过 create_all 创建的旧库 ──
    # 跳过全部建表操作，仅记录日志。main.py 会执行 stamp head 标记此迁移已完成。
    if _table_exists(bind, 'users'):
        print("[migration] 检测到已有数据库（users 表已存在），跳过初始建表")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('lock_version', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_lock_version'), 'agent_sessions', ['lock_version'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvases',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvases_user_id'), 'canvases', ['user_id'], unique=False)
    op.create_table('collaboration_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('canvas_id', GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_events_canvas_id'), 'collaboration_events', ['canvas_id'], unique=False)
    op.create_table('failed_refunds',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_refunds_user_id'), 'failed_refunds', ['user_id'], unique=False)
    op.create_table('ip_assets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearance_desc', sa.Text(), nullable=True),
    sa.Column('outfit_desc', sa.Text(), nullable=True),
    sa.Column('immutable_features', sa.JSON(), nullable=True),
    sa.Column('visual_anchors', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('reference_urls', sa.JSON(), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('genre_tags', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('source_canvas_id', GUID(), nullable=True),
    sa.Column('source_project_name', sa.String(length=255), nullable=True),
    sa.Column('reuse_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ip_assets_public', 'ip_assets', ['is_public'], unique=False)
    op.create_index('idx_ip_assets_user_type', 'ip_assets', ['user_id', 'asset_type'], unique=False)
    op.create_index(op.f('ix_ip_assets_user_id'), 'ip_assets', ['user_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('credits_5s', sa.Integer(), nullable=False),
    sa.Column('credits_10s', sa.Integer(), nullable=False),
    sa.Column('credits_15s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_model_id'), 'model_configs', ['model_id'], unique=True)
    op.create_index(op.f('ix_model_configs_type'), 'model_configs', ['type'], unique=False)
    op.create_table('recharge_tiers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('yuan', sa.Float(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_conversations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('skill_title', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_conversations_skill_id'), 'skill_conversations', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_conversations_user_id'), 'skill_conversations', ['user_id'], unique=False)
    op.create_table('sms_codes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_codes_phone'), 'sms_codes', ['phone'], unique=False)
    op.create_index('ix_sms_codes_phone_created_at', 'sms_codes', ['phone', 'created_at'], unique=False)
    op.create_table('task_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('canvas_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_records_canvas_id'), 'task_records', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_task_records_node_id'), 'task_records', ['node_id'], unique=False)
    op.create_index(op.f('ix_task_records_status'), 'task_records', ['status'], unique=False)
    op.create_index(op.f('ix_task_records_user_id'), 'task_records', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('invited_by', GUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('assets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('canvas_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'CHARACTER', 'SCENE', 'OTHER', name='assettype'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_canvas_id'), 'assets', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('canvas_collaborators',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('canvas_id', GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', 'COMMENTER', name='collaboratorrole'), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=True),
    sa.Column('invite_status', sa.String(length=50), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_id', 'user_id', name='uq_canvas_user')
    )
    op.create_index(op.f('ix_canvas_collaborators_canvas_id'), 'canvas_collaborators', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_canvas_collaborators_user_id'), 'canvas_collaborators', ['user_id'], unique=False)
    op.create_table('canvas_snapshots',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('canvas_id', GUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_snapshots_canvas_id'), 'canvas_snapshots', ['canvas_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_ref_id'), 'credit_ledger', ['ref_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('ip_asset_relations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('ip_asset_id', GUID(), nullable=False),
    sa.Column('related_asset_id', GUID(), nullable=True),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('relation_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ip_asset_id'], ['ip_assets.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['ip_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_asset_relations_ip_asset_id'), 'ip_asset_relations', ['ip_asset_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('canvas_id', GUID(), nullable=False),
    sa.Column('node_type', sa.Enum('CHARACTER', 'SCENE', 'SCRIPT', 'STORYBOARD', 'IMAGE', 'VIDEO', 'AUDIO', 'GROUP', name='nodetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', name='nodestatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('result_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_canvas_id'), 'nodes', ['canvas_id'], unique=False)
    op.create_table('recharge_orders',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('out_trade_no', sa.String(length=128), nullable=False),
    sa.Column('amount_yuan', sa.Float(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trade_no', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_orders_channel'), 'recharge_orders', ['channel'], unique=False)
    op.create_index(op.f('ix_recharge_orders_out_trade_no'), 'recharge_orders', ['out_trade_no'], unique=True)
    op.create_index(op.f('ix_recharge_orders_status'), 'recharge_orders', ['status'], unique=False)
    op.create_index(op.f('ix_recharge_orders_user_id'), 'recharge_orders', ['user_id'], unique=False)
    op.create_table('redeem_codes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redeem_codes_batch_id'), 'redeem_codes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_redeem_codes_code'), 'redeem_codes', ['code'], unique=True)
    op.create_table('skill_messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('conversation_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('params_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['skill_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_messages_conversation_id'), 'skill_messages', ['conversation_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('canvas_id', GUID(), nullable=False),
    sa.Column('source_node_id', GUID(), nullable=False),
    sa.Column('target_node_id', GUID(), nullable=False),
    sa.Column('edge_type', sa.Enum('DEFAULT', 'SEQUENCE', 'REFERENCE', 'ASSOCIATION', name='edgetype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'edge_type', name='uq_edge_src_tgt_type')
    )
    op.create_index(op.f('ix_edges_canvas_id'), 'edges', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_edges_source_node_id'), 'edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_edges_target_node_id'), 'edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_target_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_canvas_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_skill_messages_conversation_id'), table_name='skill_messages')
    op.drop_table('skill_messages')
    op.drop_index(op.f('ix_redeem_codes_code'), table_name='redeem_codes')
    op.drop_index(op.f('ix_redeem_codes_batch_id'), table_name='redeem_codes')
    op.drop_table('redeem_codes')
    op.drop_index(op.f('ix_recharge_orders_user_id'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_status'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_out_trade_no'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_channel'), table_name='recharge_orders')
    op.drop_table('recharge_orders')
    op.drop_index(op.f('ix_nodes_canvas_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_ip_asset_relations_ip_asset_id'), table_name='ip_asset_relations')
    op.drop_table('ip_asset_relations')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_ref_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_canvas_snapshots_canvas_id'), table_name='canvas_snapshots')
    op.drop_table('canvas_snapshots')
    op.drop_index(op.f('ix_canvas_collaborators_user_id'), table_name='canvas_collaborators')
    op.drop_index(op.f('ix_canvas_collaborators_canvas_id'), table_name='canvas_collaborators')
    op.drop_table('canvas_collaborators')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_canvas_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_records_user_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_status'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_node_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_canvas_id'), table_name='task_records')
    op.drop_table('task_records')
    op.drop_index('ix_sms_codes_phone_created_at', table_name='sms_codes')
    op.drop_index(op.f('ix_sms_codes_phone'), table_name='sms_codes')
    op.drop_table('sms_codes')
    op.drop_index(op.f('ix_skill_conversations_user_id'), table_name='skill_conversations')
    op.drop_index(op.f('ix_skill_conversations_skill_id'), table_name='skill_conversations')
    op.drop_table('skill_conversations')
    op.drop_table('recharge_tiers')
    op.drop_index(op.f('ix_model_configs_type'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_model_id'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_ip_assets_user_id'), table_name='ip_assets')
    op.drop_index('idx_ip_assets_user_type', table_name='ip_assets')
    op.drop_index('idx_ip_assets_public', table_name='ip_assets')
    op.drop_table('ip_assets')
    op.drop_index(op.f('ix_failed_refunds_user_id'), table_name='failed_refunds')
    op.drop_table('failed_refunds')
    op.drop_index(op.f('ix_collaboration_events_canvas_id'), table_name='collaboration_events')
    op.drop_table('collaboration_events')
    op.drop_index(op.f('ix_canvases_user_id'), table_name='canvases')
    op.drop_table('canvases')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_lock_version'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
